services:
  threewygo_backend:
    container_name: threewygo_backend
    working_dir: /threewygo_backend
    build:
      context: ./threewygo_backend
    volumes:
      - ./threewygo_backend:/threewygo_backend
      - rubygems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  database:  
  rubygems: